####
#Subsetting data for data relevant to 2016 mega experiment:
#
setwd("/Users/Shelly/Desktop/2016-17_CrabExp_WaterChem/data/")
mega_selects <- read_xlsx("crab OA omics samples 2016.xlsx", sheet = 3, skip = 2)
mega_selects <- mega_selects[,c(1,3,6)]
mega_selects <- unique(mega_selects)
mega_selects$MOATS <- substr(mega_selects$MOATS, 2,3)
mega_selects$MOATS <- as.numeric(mega_selects$MOATS)
mega_selects <- mega_selects[order(mega_selects$MOATS),]
mega_2016_dates <- data.frame()
for (i in 1:nrow(mega_selects)){
  dates <- data.frame(seq(mega_selects$startDate[i],mega_selects$freezeDate[i], by = "days"))
  colnames(dates) <- "Date"
  dates$MOATS <- mega_selects$MOATS[i]
  mega_2016_dates <- rbind(mega_2016_dates, dates)
}
mega_2016_dates <- unique(mega_2016_dates)
mega_2016_dates$Date <- as.POSIXct(strptime(mega_2016_dates$Date, format = "%Y-%m-%d"))
mega_2016_data <- merge(mega_2016_dates, d_unfiltered, by = c("Date", "MOATS"))

#merge data frames
#next line duplicates each MOATS data line for dates that have spec data because there are two jars per MOATS
#Spec_pH[,-c(6,7)] excludes 'treatment' and 'data_type' column from Spec data
#using all.x = TRUE to exclude any spec data that doesn't relate to MOATS
mega_2016_data <- merge(mega_2016_data,Spec_pH[,-c(6,7)],by = c("MOATS", "Date"),all.x = TRUE)
#presens[,-3] excludes 'data_type' column
#using all.x = TRUE to exclude any presens data that doesn't relate to MOATS and experiment dates
mega_2016_data <- merge(mega_2016_data, presens[,-3], by = c("MOATS", "Date"), all.x = TRUE)
#am no longer running the following line because Spec_pH data salinity column now matches the salinity file
#Master_data <- merge(Master_data, salinity, by = "Date", all = TRUE)
#PMEL_for_Master[,-c(3,4,8,9)] excludes muk salinity values and PMEL salinity values (since these are in the 'Salinity_for_SxTA' column) and 'data_type' and 'experiments' columns
#using all.x = TRUE here because want to exclude PMEL data for dates outside of experiments
mega_2016_data <- merge(mega_2016_data, PMEL_for_Master[,-c(3,4,8,9)], by = c("MOATS", "Date"), all.x = TRUE)

#make a table with the mean daily temp that can be merged with master data
#standard dev. is included to see if any weird data is present
MeanDailyTemp <- mega_2016_data[which(mega_2016_data$OL < 25 & mega_2016_data$OL > 4),] %>% group_by(Date,MOATS) %>% summarize(meanT = mean(OL), stdevT = sd(OL))
#merge MeanDailyTemp with Master_data and exclude stdev column
mega_2016_data <- merge(mega_2016_data, MeanDailyTemp[,-4], by = c("MOATS", "Date"))
mega_2016_data$Data_Type <- NULL
#merge treatment data with rest of data
mega_2016_data <- merge(mega_2016_data,dtreat, by = c("MOATS", "Date"))
#save mega data as 'data'
data <- mega_2016_data

#convert pH at 25C to pH at 12C
for (i in 1:length(data$Date)){
  print(i)
  if(!is.na(data$pH_at_25C[i]) && !is.na(data$meanT[i])){
    #date <- data[i,which(colnames(data)=="Date")]
    Sal <- data$Salinity[i]
    #calculate TA ('alk') from salinity values using the slope and intercept generated by 'Alkalinity v Salinity_KD_2018.R' script. This script compared Fassbender et al 2016 data to data from Muk (Chase's and our data from the past two years). This way, we were able to figure out what our offset is here at Muk.
    TAcalc <- ((50.946 * Sal)+522.506)/1000000
    pHspec <- data$pH_at_25C[i]
    Temp <- data$meanT[i]
    data$carbSpecDIC[i] <- carb(flag = 8, pHspec, TAcalc, Sal,T=25)$DIC
    data$carbSpecpH[i] <- carb(flag = 15, TAcalc,as.numeric(data$carbSpecDIC[i]), Sal,Temp)$pH
  }
  else{
    data$carbSpecDIC[i] <- "NA"
    data$carbSpecpH[i] <- "NA"
  }
}

class(data$carbSpecpH) <- "numeric"
class(data$carbSpecDIC) <- "numeric"
data$carbSpecDIC <- data$carbSpecDIC *1000000
data$Date <- as.Date(data$Date)
data$MOATS <- as.numeric(data$MOATS)
#write.csv(data, "~/Desktop/2016-17_CrabExp_WaterChem/data.csv", quote = FALSE, row.names = FALSE)
data <- data[which(data$pH > 0),]

########
#Compare to MOATS pH
########
#create empty DF for pH and DO stats
pH_stats <- data.frame()
DO_stats <- data.frame()

#for (i in 1:length(treats)){
  #create an empty data frame
  #exp <- data[which(data$Date >= as.Date(treats[[i]]$Start_Date[i]) & data$Date <= as.Date(treats[[i]]$End_Date[i])),]
  exp <- data
  exp$datetime <- as.POSIXct(paste(exp$Date,exp$Time), format="%Y-%m-%d %H:%M:%S")
  colnames(exp)[4] <- "MOATSpH"
  colnames(exp)[7] <- "MOATSDO"
  #prepare tables for plotting pH and DO data
  exp_pH <- tidyr::gather(exp, "source", "pH",c(4,ncol(exp)-1))
  exp_DO <- tidyr::gather(exp, "source", "DO", c(7,12))
  
  #loop through each experimental pH condition and generate plots for data from each MOATS 
  for (j in 1:length(unique(exp_pH$Target_pH))){
    exppH <- unique(exp_pH$Target_pH)[j]
    #time series plot of MOATS pH and Spec pH data
    #p1 <- ggplot(exp_pH[which(exp_pH$Target_pH == exppH),], aes(x= datetime, y= pH)) + geom_point(aes(colour = source)) + scale_x_datetime("datetime", date_breaks = "day", date_labels = "%b %d", expand = c(0,0), minor_breaks = NULL) + xlab("Date") + facet_wrap(~MOATS) + ggtitle(paste(treats[[i]]$Experiment[i],treats[[i]]$Start_Date[i],treats[[i]]$End_Date[i],"pH",exppH, sep = "_")) + theme(axis.text.x=element_text(angle = 90, hjust = 0))
   p1 <- ggplot(exp_pH[which(exp_pH$Target_pH == exppH),], aes(x= datetime, y= pH)) + geom_point(aes(colour = source)) + scale_x_datetime("datetime", date_breaks = "day", date_labels = "%b %d", expand = c(0,0), minor_breaks = NULL) + xlab("Date")  + facet_wrap(~MOATS) + ggtitle(paste(data$Experiment[1],data$Start_Date[1],data$Start_Date[nrow(data)],"pH",exppH, sep = "_")) + theme(axis.text.x=element_text(angle = 90, hjust = 0))
    
    #create a unique id for plot filename that contains the experiment subject, start and end date, and specific chemistry parameter
    #id <- paste(treats[[i]]$Experiment[i],treats[[i]]$Start_Date[i],treats[[i]]$End_Date[i],"pH",exppH,sep = "_")
    id <- paste(data$Experiment[1],data$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH,sep = "_")
    
    #preparing data for generating boxplots of MOATS pH data distributions over course of experiment
    #use unique command to remove duplicate lines that are included for overlapping experiments and exclude experiment column
    if(exppH == 7.8){
    exppH_short <- unique(exp_pH[which(exp_pH$Target_pH == 7.8 & exp_pH$source == "MOATSpH" & exp_pH$MOATS != 5 & exp_pH$MOATS != 12),-8])
    exppH_short <- rbind(exppH_short, exp_pH[which(
      exp_pH$source == "carbSpecpH" & exp_pH$MOATS == 5 |
      exp_pH$source == "carbSpecpH" &exp_pH$MOATS == 12),-8])
    }
    else{
      exppH_short <- unique(exp_pH[which(exp_pH$Target_pH == exppH & exp_pH$source == "MOATSpH"),-8])
    }
    #boxplots of MOATS pH distributions
    #p2 <- ggplot(exppH_short, aes(as.character(MOATS), pH)) + geom_boxplot(aes(fill= pH)) + xlab("MOATS") + ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH, sep = "_"))
    #p3 <- ggplot(exppH_short, aes(as.character(MOATS), pH)) + geom_violin(aes(fill = pH)) + geom_boxplot(aes(fill= pH), width = 0.1) + facet_wrap(~MOATS, scale = "free") + xlab("MOATS") + ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH, sep = "_"))
    
   p2 <- ggplot(exppH_short, aes(as.character(MOATS), pH)) + geom_violin(aes(fill= pH)) + 
      geom_point(aes(as.character(MOATS), pH)) + 
      stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                   geom="pointrange", color="orange") + xlab("MOATS") + 
      ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH, sep = "_"))
    
   p3 <- ggplot(exppH_short, aes(as.character(MOATS), pH)) + geom_violin(aes(fill = pH)) + 
     geom_point(aes(as.character(MOATS), pH)) + 
     stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                  geom="pointrange", color="orange") + 
     facet_wrap(~MOATS, scale = "free") + xlab("MOATS") + 
     ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH, sep = "_"))
   
    
    #boxplot of spec pH values for MOATS 5 and 12 since their probes acted funny
    #ggplot(exp_pH[which(exp_pH$source == "carbSpecpH" & exp_pH$MOATS == 5 |
#                           exp_pH$source == "carbSpecpH" &exp_pH$MOATS == 12),], 
#                          aes(as.character(MOATS), pH)) + geom_boxplot(aes(fill= pH)) + 
#                          geom_point(aes(as.character(MOATS), pH)) + 
#                         stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
#                         geom="pointrange", color="orange") + xlab("MOATS") + 
#                         ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"pH",exppH, sep = "_"))
#     
    #create a stats table with mean, standard deviation, and standard error
    means <- aggregate(pH ~  MOATS, exppH_short, mean)
    sds <- aggregate(pH ~  MOATS, exppH_short, sd)
    #ses <- aggregate(pH ~  MOATS, exppH_short, plotrix::std.error)
    sumstats <- merge(means, sds, by = "MOATS")
    #sumstats <- merge(sumstats, ses, by = "MOATS")
    #colnames(sumstats) <- c("MOATS", "mean", "stdev", "stderr")
    colnames(sumstats) <- c("MOATS", "mean", "stdev")
    
    #add experiment column to stats table to distiguish stats
    sumstats$experiment <- id
    sumstats$MOATS_total_mean <- mean(exppH_short$pH, na.rm = TRUE)
    sumstats$MOATS_total_sd <- sd(exppH_short$pH, na.rm = TRUE)
    #sumstats$MOATS_total_se <- std.error(exppH_short$pH)
    sumstats$Spec_total_mean <- mean(exp_pH[which(exp_pH$Target_pH == exppH & exp_pH$source == "carbSpecpH"),"pH"], na.rm = TRUE)
    sumstats$Spec_total_sd <- sd(exp_pH[which(exp_pH$Target_pH == exppH & exp_pH$source == "carbSpecpH"),"pH"], na.rm = TRUE)
    #sumstats$Spec_total_se <- std.error(exp_pH[which(exp_pH$Target_pH == exppH & exp_pH$source == "carbSpecpH"),"pH"])
    pH_stats <- rbind(pH_stats,sumstats)
    
    #save plots of pH data comparisons
    ggsave(p1, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/pH/",id,".pdf", sep =""), width = 30, height = 10)
    ggsave(p2, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/pH/",id,"_allbox.pdf", sep =""), width = 7, height = 7)
    ggsave(p3, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/pH/",id,"_indvbox.pdf", sep =""), width = 7, height = 7)
  }
  #loop through each experimental DO condition and generate plots for data from each MOATS 
  for (k in 1:length(unique(exp_DO$Target_DO))){
    expDO <- unique(exp_DO$Target_DO)[k]
    p1 <- ggplot(exp_DO[grep(expDO,exp_DO$Target_DO),], aes(x= datetime, y= DO)) + geom_point(aes(colour = source)) + scale_x_datetime("datetime", date_breaks = "day", date_labels = "%b %d", expand = c(0,0), minor_breaks = NULL) + xlab("Date") + facet_wrap(~MOATS) + ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO, sep = "_")) + theme(axis.text.x=element_text(angle = 90, hjust = 0))
    
    #create a unique id for plot filename that contains the experiment subject, start and end date, and specific chemistry parameter
    id <- paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO,sep = "_")
    
    #preparing data for generating boxplots of MOATS DO data distributions over course of experiment
    #use unique command to remove duplicate lines that are included for overlapping experiments and exclude experiment column
    expDO_short <- unique(exp_DO[which(exp_DO$Target_DO == expDO & exp_DO$source == "MOATSDO"),-8])
    
    #boxplots of MOATS DO distributions
   #p2 <- ggplot(expDO_short, aes(as.character(MOATS), DO)) + geom_boxplot(aes(fill= DO)) + xlab("MOATS") + ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO, sep = "_"))
    #p3 <- ggplot(expDO_short, aes(as.character(MOATS), DO)) + geom_violin(aes(fill = DO)) + geom_boxplot(aes(fill= DO), width = 0.1) + facet_wrap(~MOATS, scale = "free") + xlab("MOATS") + ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO, sep = "_"))
    
    p2 <- ggplot(expDO_short, aes(as.character(MOATS), DO)) + geom_violin(aes(fill= DO)) + 
      geom_point(aes(as.character(MOATS), DO)) + 
      stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                   geom="pointrange", color="orange") + xlab("MOATS") + 
      ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO, sep = "_"))
    
    p3 <- ggplot(expDO_short, aes(as.character(MOATS), DO)) + geom_violin(aes(fill = DO)) + 
      geom_point(aes(as.character(MOATS), DO)) + 
      stat_summary(fun.data=mean_sdl, fun.args = list(mult=1), 
                   geom="pointrange", color="orange") + 
      facet_wrap(~MOATS, scale = "free") + xlab("MOATS") + 
      ggtitle(paste(treats[[3]]$Experiment[1],treats[[3]]$Start_Date[1],treats[[3]]$End_Date[1],"DO",expDO, sep = "_"))
    
    
    
    
    #create a stats table with mean, standard deviation, and standard error
    means <- aggregate(DO ~  MOATS, expDO_short, mean)
    sds <- aggregate(DO ~  MOATS, expDO_short, sd)
    ses <- aggregate(DO ~  MOATS, expDO_short, plotrix::std.error)
    sumstats <- merge(means, sds, by = "MOATS")
    sumstats <- merge(sumstats, ses, by = "MOATS")
    colnames(sumstats) <- c("MOATS", "mean", "stdev", "stderr")
    
    #add experiment column to stats table to distiguish stats
    sumstats$experiment <- id
    sumstats$MOATS_total_mean <- mean(expDO_short$DO, na.rm = TRUE)
    sumstats$MOATS_total_sd <- sd(expDO_short$DO, na.rm = TRUE)
    sumstats$MOATS_total_se <- std.error(expDO_short$DO)
    sumstats$Presens_total_mean <- mean(exp_DO[which(exp_DO$Target_DO == expDO & exp_DO$source == "presensDO"),"DO"], na.rm = TRUE)
    sumstats$Presens_total_sd <- sd(exp_DO[which(exp_DO$Target_DO == expDO & exp_DO$source == "presensDO"),"DO"], na.rm = TRUE)
    sumstats$Presens_total_se <- std.error(exp_DO[which(exp_DO$Target_DO == expDO & exp_DO$source == "presensDO"),"DO"])
    DO_stats <- rbind(DO_stats,sumstats)
    
    #save plots of DO data comparisons
    ggsave(p1, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/DO/",id,".pdf", sep =""), width = 30, height = 10)
    ggsave(p2, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/DO/",id,"_allbox.pdf", sep =""), width = 5, height = 5)
    ggsave(p3, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/DO/",id,"_indvbox.pdf", sep =""), width = 5, height = 5)
    
  }
}

#gives warning message: removed 14638 rows containing missing values (geom_point). This is because of the days that no Spec pH was taken.
#Here is the code that shows that:
#View(exp[which(exp$Target_pH ==7.4 & is.na(exp$pH)),])
overall_pH_stats <- unique(pH_stats[,5:ncol(pH_stats)])
overall_DO_stats <- unique(DO_stats[,5:ncol(DO_stats)])
indv_MOATS_pH_stats <- pH_stats[,1:5]
indv_MOATS_DO_stats <- DO_stats[,1:5]

write.csv(overall_pH_stats,"~/Desktop/2016-17_CrabExp_WaterChem/data/overall_pH_stats.csv", row.names = FALSE, quote = FALSE)
write.csv(overall_DO_stats,"~/Desktop/2016-17_CrabExp_WaterChem/data/overall_DO_stats.csv", row.names = FALSE, quote = FALSE)
write.csv(indv_MOATS_DO_stats,"~/Desktop/2016-17_CrabExp_WaterChem/data/indv_MOATS_DO_stats.csv", row.names = FALSE, quote = FALSE)
write.csv(indv_MOATS_pH_stats,"~/Desktop/2016-17_CrabExp_WaterChem/data/indv_MOATS_pH_stats.csv", row.names = FALSE, quote = FALSE)

###calculate mean and SD for temperature 
mean(data[which(data$Target_pH == 7.4 & data$Target_DO == 3),"meanT"])
# 12.154
sd(data[which(data$Target_pH == 7.4 & data$Target_DO == 3),"meanT"])
# 0.07797686
mean(data[which(data$Target_pH == 7.4 & data$Target_DO == 8.5),"meanT"])
#12.14349
sd(data[which(data$Target_pH == 7.4 & data$Target_DO == 8.5),"meanT"])
# 0.04445763
mean(data[which(data$Target_pH == 7.8 & data$Target_DO == 3),"meanT"])
#12.1184
sd(data[which(data$Target_pH == 7.8 & data$Target_DO == 3),"meanT"])
# 0.06160899
mean(data[which(data$Target_pH == 7.8 & data$Target_DO == 8.5),"meanT"])
# 12.16791
sd(data[which(data$Target_pH == 7.8 & data$Target_DO == 8.5),"meanT"])
# 0.08950604


mean(data[which(data$Target_pH == 7.4 & data$Target_DO == 3 & data$OL < 25 & data$OL > 4),"OL"])
#12.154
sd(data[which(data$Target_pH == 7.4 & data$Target_DO == 3 & data$OL < 25 & data$OL > 4),"OL"])
#0.1618713
mean(data[which(data$Target_pH == 7.4 & data$Target_DO == 8.5 & data$OL < 25 & data$OL > 4),"OL"])
#12.14349
sd(data[which(data$Target_pH == 7.4 & data$Target_DO == 8.5 & data$OL < 25 & data$OL > 4),"OL"])
#0.07881796
mean(data[which(data$Target_pH == 7.8 & data$Target_DO == 3 & data$OL < 25 & data$OL > 4),"OL"])
#12.1184
sd(data[which(data$Target_pH == 7.8 & data$Target_DO == 3 & data$OL < 25 & data$OL > 4),"OL"])
#0.1196115
mean(data[which(data$Target_pH == 7.8 & data$Target_DO == 8.5 & data$OL < 25 & data$OL > 4),"OL"])
#12.16789
sd(data[which(data$Target_pH == 7.8 & data$Target_DO == 8.5 & data$OL < 25 & data$OL > 4),"OL"])
#0.1645288

###calculate mean and SD for DO; 
##MOATS 5 and 12 had probe malfunction and feedback feature was turned off, so only using the presens data for these MOATS
##For all other MOATS, using the logger probe data

mean(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.4 & exp_DO$Target_DO == 3),"DO"])
#[1] 3.033963
sd(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.4 & exp_DO$Target_DO == 3),"DO"])
#[1] 0.3095011
mean(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.4 & exp_DO$Target_DO == 8.5),"DO"])
#8.899971
sd(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.4 & exp_DO$Target_DO == 8.5),"DO"])
#[1] 0.08558688

mean(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.8 & exp_DO$Target_DO == 3),"DO"])
#[1] 3.000776
sd(exp_DO[which(exp_DO$source == "MOATSDO" & exp_DO$Target_pH == 7.8 & exp_DO$Target_DO == 3),"DO"])
#[1] 0.1324804

##using presens data for MOATS 5 and 12, and logger data for other MOATS
expDO_short512 <- unique(exp_DO[which(exp_DO$Target_DO == 8.5 & exp_DO$source == "MOATSDO" & exp_DO$MOATS != 5 & exp_DO$MOATS != 12),-8])
expDO_short512 <- rbind(expDO_short512, exp_DO[which(exp_DO$Target_DO == 8.5 & exp_DO$source == "presensDO" & exp_DO$MOATS == 5 |exp_DO$Target_DO ==8.5 & exp_DO$source == "presensDO" &exp_DO$MOATS == 12),-8])
expDO_short512 <- unique(expDO_short512[,c("MOATS", "Date", "Target_pH","Target_DO","source", "DO")])
mean(expDO_short512[which(expDO_short512$Target_pH == 7.8 & expDO_short512$Target_DO == 8.5),"DO"],na.rm = TRUE)
#[1] 8.899948
sd(expDO_short512[which(expDO_short512$Target_pH == 7.8 & expDO_short512$Target_DO == 8.5),"DO"],na.rm = TRUE)
#[1] 0.1668212

 

###calculate mean and SD for pH; for MOATS 5 and 12, Spec pH was used, for every other MOATS, MOATS probe pH was used

###
exppH_short512 <- unique(exp_pH[which(exp_pH$Target_pH == 7.8 & exp_pH$source == "MOATSpH" & exp_pH$MOATS != 5 & exp_pH$MOATS != 12),-8])
exppH_short512 <- rbind(exppH_short512, exp_pH[which(exp_pH$source == "carbSpecpH" & exp_pH$Target_pH ==7.8 & exp_pH$MOATS == 5 |exp_pH$source == "carbSpecpH" & exp_pH$Target_pH == 7.8 & exp_pH$MOATS == 12),-8])
exppH_short512 <- unique(exppH_short512[,c("MOATS", "Date", "Target_pH","Target_DO","source", "pH")])
mean(exppH_short512[which(exppH_short512$Target_pH == 7.8 & exppH_short512$Target_DO == 8.5),"pH"],na.rm = TRUE)
#[1] 7.830239
sd(exppH_short512[which(exppH_short512$Target_pH == 7.8 & exppH_short512$Target_DO == 8.5),"pH"],na.rm = TRUE)
#[1] 0.04524201
mean(exppH_short[which(exppH_short$Target_pH == 7.8 & exppH_short$Target_DO == 3.0),"pH"],na.rm = TRUE)
#[1] 7.84636
sd(exppH_short[which(exppH_short$Target_pH == 7.8 & exppH_short$Target_DO == 3.0),"pH"],na.rm = TRUE)
#[1] 0.01654367

mean(exppH_short[which(exppH_short$Target_pH == 7.4 & exppH_short$Target_DO == 8.5),"pH"])
#[1] 7.45451
sd(exppH_short[which(exppH_short$Target_pH == 7.4 & exppH_short$Target_DO == 8.5),"pH"])
#[1] 0.05366982
mean(exppH_short[which(exppH_short$Target_pH == 7.4 & exppH_short$Target_DO == 3),"pH"])
#[1] 7.490414
sd(exppH_short[which(exppH_short$Target_pH == 7.4 & exppH_short$Target_DO == 3),"pH"])
#[1] 0.1074502


Data_for_paper <- data[,c(27,1,9,2,8,4,5,7,26,12,10,14,13)]
colnames(Data_for_paper) <- c("Target_Treatment", "MOATS", "Jar", "Date", "Time", "pH_logger", "Temp_logger","DO_logger","Spec_pH", "PresensDO", "Salinity", "Total_Alkalinity", "DIC")
Data_for_paper$Target_Treatment <- gsub("7.4","7.45", Data_for_paper$Target_Treatment)
Data_for_paper$Target_Treatment <- gsub("7.8","7.85", Data_for_paper$Target_Treatment)
Data_for_paper$Target_Treatment <- gsub("8.5","8.9", Data_for_paper$Target_Treatment)
Data_for_paper$Target_Treatment <- gsub("3","3.0", Data_for_paper$Target_Treatment)

Data_for_paper <- Data_for_paper[order(Data_for_paper$Date, Data_for_paper$MOATS, Data_for_paper$Time),]

write.csv(Data_for_paper, "~/Desktop/UCSD-SALK/NOAA/metabolomics/manuscript_draft/supplementary_tables/WaterChem.csv", quote = FALSE, row.names = FALSE)


DataLogger_for_paper <- unique(Data_for_paper[,-c(3,9:13)])

DataDiscrete_for_paper <- unique(Data_for_paper[,c(1:4,9:13)])
DataDiscrete_for_paper <- DataDiscrete_for_paper[which(!is.na(DataDiscrete_for_paper$Spec_pH)| 
                                                         !is.na(DataDiscrete_for_paper$PresensDO) | !is.na(DataDiscrete_for_paper$Salinity)| 
                                                       !is.na(DataDiscrete_for_paper$Total_Alkalinity)| !is.na(DataDiscrete_for_paper$DIC)),]

New_data_for_paper <- data.frame(matrix(ncol = 13, nrow = 0))
colnames(New_data_for_paper) <- colnames(Data_for_paper)

New_data_for_paper <- merge(New_data_for_paper, DataLogger_for_paper, all = TRUE)
New_data_for_paper <- merge(New_data_for_paper, DataDiscrete_for_paper, all = TRUE)

mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment=="pH_7.45_DO_3.0"),"pH_logger"],na.rm = TRUE)
###see if DO avgs and sds match up with previously calculated ones now that non-unique rows are excluded
New_data_for_paper_DO <- tidyr::gather(New_data_for_paper, "source", "DO", c(6,13))
New_data_for_paper_DO <- New_data_for_paper_DO[which(New_data_for_paper_DO$source =="PresensDO" & New_data_for_paper_DO$MOATS ==5 | 
                                                       New_data_for_paper_DO$source =="PresensDO" & New_data_for_paper_DO$MOATS ==12 | 
                                                       New_data_for_paper_DO$source =="DO_logger" & New_data_for_paper_DO$MOATS !=5 &
                                                 New_data_for_paper_DO$MOATS !=12),]

mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_8.9"),"DO"], na.rm = TRUE)
sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_8.9"),"DO"], na.rm = TRUE)
mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_3.0"),"DO"], na.rm = TRUE)
sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_3.0"),"DO"], na.rm = TRUE)
mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_8.9"),"DO"], na.rm = TRUE)
sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_8.9"),"DO"], na.rm = TRUE)
mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_3.0"),"DO"], na.rm = TRUE)
sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_3.0"),"DO"], na.rm = TRUE)
###****The numbers are all the same
#> mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_8.9"),"DO"], na.rm = TRUE)
#[1] 8.899948
#> sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_8.9"),"DO"], na.rm = TRUE)
#[1] 0.1668212
#> mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_3.0"),"DO"], na.rm = TRUE)
#[1] 3.001348
#> sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.85_DO_3.0"),"DO"], na.rm = TRUE)
#[1] 0.1437038
#> mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_8.9"),"DO"], na.rm = TRUE)
#[1] 8.899999
#> sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_8.9"),"DO"], na.rm = TRUE)
#[1] 0.08670711
#> mean(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_3.0"),"DO"], na.rm = TRUE)
#[1] 3.03862
#> sd(New_data_for_paper_DO[which(New_data_for_paper_DO$Target_Treatment == "pH_7.45_DO_3.0"),"DO"], na.rm = TRUE)
#[1] 0.3191764

###see if pH avgs and sds match up with previously calculated ones now that non-unique rows are excluded
New_data_for_paper_pH <- tidyr::gather(New_data_for_paper, "source", "pH", c(5,11))
New_data_for_paper_pH <- New_data_for_paper_pH[which(New_data_for_paper_pH$source =="Spec_pH" & New_data_for_paper_pH$MOATS ==5 | 
                                                       New_data_for_paper_pH$source =="Spec_pH" & New_data_for_paper_pH$MOATS ==12 | 
                                                       New_data_for_paper_pH$source =="pH_logger" & New_data_for_paper_pH$MOATS !=5 &
                                                       New_data_for_paper_pH$MOATS !=12),]

mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_8.9"),"pH"], na.rm = TRUE)
sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_8.9"),"pH"], na.rm = TRUE)
mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_3.0"),"pH"], na.rm = TRUE)
sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_3.0"),"pH"], na.rm = TRUE)
mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_8.9"),"pH"], na.rm = TRUE)
sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_8.9"),"pH"], na.rm = TRUE)
mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_3.0"),"pH"], na.rm = TRUE)
sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_3.0"),"pH"], na.rm = TRUE)

###****The numbers are all the same
# > mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_8.9"),"pH"], na.rm = TRUE)
# [1] 7.830239
# > sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_8.9"),"pH"], na.rm = TRUE)
# [1] 0.04524201
# > mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_3.0"),"pH"], na.rm = TRUE)
# [1] 7.846208
# > sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.85_DO_3.0"),"pH"], na.rm = TRUE)
# [1] 0.0161219
# > mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_8.9"),"pH"], na.rm = TRUE)
# [1] 7.453555
# > sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_8.9"),"pH"], na.rm = TRUE)
# [1] 0.05033407
# > mean(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_3.0"),"pH"], na.rm = TRUE)
# [1] 7.489451
# > sd(New_data_for_paper_pH[which(New_data_for_paper_pH$Target_Treatment == "pH_7.45_DO_3.0"),"pH"], na.rm = TRUE)
# [1] 0.1058255

###check temp is the same

mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_8.9" & 
                                New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_8.9" & 
                                  New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_3.0" & 
                                New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_3.0" & 
                              New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_8.9" & 
                                New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_8.9" & 
                              New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_3.0" & 
                                New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_3.0" & 
                              New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
###***It is the same except for the ambient condition which had an SD of 0.17 instead of 0.16, not a big deal
# > mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_8.9" & 
#                                   +                                 New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 12.16666
# > sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_8.9" & 
#                                 +                                   New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 0.1671037
# > mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_3.0" & 
#                                   +                                 New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 12.11787
# > sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.85_DO_3.0" & 
#                                 +                               New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 0.1211153
# > mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_8.9" & 
#                                   +                                 New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 12.144
# > sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_8.9" & 
#                                 +                               New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 0.07956032
# > mean(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_3.0" & 
#                                   +                                 New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 12.15344
# > sd(New_data_for_paper[which(New_data_for_paper$Target_Treatment == "pH_7.45_DO_3.0" & 
#                                 +                               New_data_for_paper$Temp_logger < 25 & New_data_for_paper$Temp_logger > 4),"Temp_logger"], na.rm = TRUE)
# [1] 0.1613431

write.csv(New_data_for_paper[,c(1,2,4,3,10,11:13,5:9)], "~/Desktop/UCSD-SALK/NOAA/metabolomics/manuscript_draft/supplementary_tables/WaterChem.csv", quote = FALSE, row.names = FALSE)


###total alkalinity at beginning of experiment and end for all MOATS (this parameter is the same across all treatments)
mega_TA <- unique(data[which(!is.na(data$TA)), c("Date", "TA")])

###salinity at beginning of experiment and end for all MOATS (this parameter is the same across all treatments)
mega_sal <- unique(data[which(!is.na(data$Salinity)), c("Date", "Salinity")])


data$class <- paste("pH",data$Target_pH,"DO",data$Target_DO, sep = "_")
data$datetime <- as.POSIXct(paste(data$Date,data$Time), format="%Y-%m-%d %H:%M:%S")
ptemp <- ggplot(data, aes(x= datetime, y= meanT)) + geom_point(aes(colour = class)) + scale_x_datetime("datetime", date_breaks = "day", date_labels = "%b %d", expand = c(0,0), minor_breaks = NULL) + xlab("Date") + ggtitle(paste(data$Experiment[1],data$Start_Date[1],data$Start_Date[nrow(data)], sep = "_")) + theme(axis.text.x=element_text(angle = 90, hjust = 0))
ggsave(ptemp, file = paste("~/Desktop/2016-17_CrabExp_WaterChem/data/plots/temp.pdf", sep =""), width = 30, height = 10)

write.csv(data, "~/Desktop/2016-17_CrabExp_WaterChem/megalopae2016_data.csv", quote = FALSE, row.names = FALSE)



p1 <- ggplot(exp_pH[which(exp_pH$Target_pH == exppH),], aes(x= datetime, y= pH)) +  + xlab("Date")  + facet_wrap(~MOATS) + ggtitle(paste(data$Experiment[1],data$Start_Date[1],data$Start_Date[nrow(data)],"pH",exppH, sep = "_")) + theme(axis.text.x=element_text(angle = 90, hjust = 0))

